# Generated by Django 3.1.4 on 2022-08-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='created_ts',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='updated_ts',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
